import React from "react";
import { Activity, Clock, AlertCircle, Mic, TrendingUp, BarChart3, AlertTriangle, FileText, Target, MessageSquareText, Sparkles } from "lucide-react";
import { PacingChart } from "./PacingChart";
import { PitchChart } from "@/components/PitchChart";

import { CircularScoreChart } from "./CircularScoreChart";
import ReactMarkdown from "react-markdown";

export interface PrintableReportTemplateProps {
    data: any;
    metrics: any;
    localContentScore?: number;
    contentAnalysis?: string;
}

// Internal reusable page component to ensure consistent A4 sizing and header/footer
const PrintablePage = ({ children, pageNum, totalPages }: { children: React.ReactNode, pageNum: number, totalPages: number }) => {
    const [date, setDate] = React.useState<string>("");

    React.useEffect(() => {
        setDate(new Date().toLocaleDateString());
    }, []);

    return (
        <div className="printable-page w-[794px] h-[1123px] bg-white text-slate-900 p-12 font-sans relative flex flex-col mb-8 shadow-lg overflow-hidden">
            {/* Header */}
            <div className="flex justify-between items-end border-b-2 border-slate-200 pb-6 mb-8 shrink-0">
                <div>
                    <h1 className="text-3xl font-bold text-slate-900 mb-1">Session Report</h1>
                    <p className="text-slate-500 text-sm">Generated by VoxLab AI Coach</p>
                </div>
                <div className="text-right">
                    <div className="text-sm font-bold text-slate-900">{date}</div>
                    <div className="text-xs text-slate-500">Page {pageNum} of {totalPages}</div>
                </div>
            </div>

            {/* Content Area - Grows to fill space */}
            <div className="flex-1 flex flex-col">
                {children}
            </div>

            {/* Footer */}
            <div className="mt-auto pt-6 border-t border-slate-200 text-center text-xs text-slate-400 shrink-0">
                VoxLab AI &bull; Private & Confidential &bull; Practice Session Analysis
            </div>
        </div>
    );
};

// Helper Component for consistency
const MetricCard = ({ title, icon: Icon, children, className = "" }: { title: string, icon: any, children: React.ReactNode, className?: string }) => (
    <div className={`p-6 rounded-2xl border border-slate-200 bg-slate-50 ${className}`}>
        <h3 className="text-sm font-bold text-slate-900 uppercase tracking-widest mb-6 flex items-center gap-2 border-b border-slate-200 pb-2">
            <Icon className="w-4 h-4 text-slate-500" /> {title}
        </h3>
        {children}
    </div>
);

export function PrintableReportTemplate({ data, metrics, localContentScore, contentAnalysis }: PrintableReportTemplateProps) {
    const fillerTotal = Object.values(metrics.fillerCounts || {}).reduce((a: any, b: any) => a + b, 0) as number;

    const getWpmColor = (wpm: number) => {
        if (wpm < 110 || wpm > 160) return "text-red-700";
        if (wpm < 130 || wpm > 155) return "text-amber-700";
        return "text-green-700";
    };

    // Calculate Pacing Buckets (Logic copied from DetailedSessionReport)
    const BUCKET_SIZE = 30;
    const words = metrics.words || [];
    const maxTime = Math.max(metrics.duration, ...(words.map((w: any) => w.endTime) || [0]), 1);
    const totalBuckets = Math.ceil(maxTime / BUCKET_SIZE);

    // Fallback if words are missing but history exists
    const pacingBuckets = words.length === 0 && Array.isArray(metrics.wpmHistory) && metrics.wpmHistory.length > 0
        ? [] // Legacy mode fallback not implemented for print to save space, relies on history chart
        : Array.from({ length: totalBuckets }, (_, i) => {
            const startTime = i * BUCKET_SIZE;
            const endTime = (i + 1) * BUCKET_SIZE;
            const bucketWords = words.filter((w: any) =>
                (w.startTime >= startTime && w.startTime < endTime) ||
                (w.endTime > startTime && w.endTime <= endTime)
            );
            const count = bucketWords.length;
            const wpm = Math.round((count / BUCKET_SIZE) * 60);
            let color = "bg-green-500";
            let textColor = "text-green-700";
            if (wpm < 110 || wpm > 155) { color = "bg-red-500"; textColor = "text-red-700"; }
            else if (wpm < 130 || wpm > 155) { color = "bg-amber-500"; textColor = "text-amber-700"; }
            return { intervalLabel: `${startTime}s – ${endTime}s`, wpm, wordCount: count, color, textColor, time: endTime };
        });

    const audioStats = metrics.audioMetrics ? {
        stats: {
            ...metrics.audioMetrics,
            pitchStdDev: metrics.audioMetrics.pitchStdDev ?? metrics.audioMetrics.pitchRange,
            quietPercentage: metrics.audioMetrics.quietPercentage ?? (metrics.audioMetrics.isTooQuiet ? 0.8 : 0.1)
        },
        feedback: {
            type: metrics.audioMetrics.isMonotone ? "warn" : "good",
            message: metrics.audioMetrics.isMonotone ? "Try varying your pitch more." : "Good tonal variety."
        }
    } : null;

    // Chunk transcript for multiple pages if it's very long
    const charsPerPage = 2500;
    const transcriptText = metrics.transcript || "";
    const transcriptChunks = [];
    for (let i = 0; i < transcriptText.length; i += charsPerPage) {
        transcriptChunks.push(transcriptText.substring(i, i + charsPerPage));
    }
    if (transcriptChunks.length === 0) transcriptChunks.push("");

    // Smarter chunking for Content Analysis to handle Markdown safely
    const contentAnalysisText = contentAnalysis || "";
    const analysisChunks: string[] = [];
    const MAX_CHUNK_SIZE = 1400; // Strict limit to guarantee no vertical overflow with rendered Markdown

    let remainingText = contentAnalysisText;
    while (remainingText.length > 0) {
        if (remainingText.length <= MAX_CHUNK_SIZE) {
            analysisChunks.push(remainingText.trim());
            break;
        }

        // Find a safe split point before MAX_CHUNK_SIZE looking backwards
        let splitIndex = MAX_CHUNK_SIZE;

        const doubleNewline = remainingText.lastIndexOf('\n\n', MAX_CHUNK_SIZE);
        if (doubleNewline > MAX_CHUNK_SIZE * 0.4) {
            splitIndex = doubleNewline;
        } else {
            const singleNewline = remainingText.lastIndexOf('\n', MAX_CHUNK_SIZE);
            if (singleNewline > MAX_CHUNK_SIZE * 0.4) {
                splitIndex = singleNewline;
            } else {
                const sentenceEnd = remainingText.lastIndexOf('. ', MAX_CHUNK_SIZE);
                if (sentenceEnd > MAX_CHUNK_SIZE * 0.4) {
                    splitIndex = sentenceEnd + 1;
                } else {
                    const space = remainingText.lastIndexOf(' ', MAX_CHUNK_SIZE);
                    if (space > 0) {
                        splitIndex = space;
                    }
                }
            }
        }

        analysisChunks.push(remainingText.substring(0, splitIndex).trim());
        remainingText = remainingText.substring(splitIndex).trim();
    }

    if (analysisChunks.length === 0) analysisChunks.push("");

    // NEW FOR Q&A
    const hasQnA = !!data.qnaSummary && data.qnaSummary.length > 0;
    const qnaChunks = [];
    if (hasQnA) {
        for (let i = 0; i < data.qnaSummary.length; i += 1) {
            qnaChunks.push(data.qnaSummary.slice(i, i + 1));
        }
    }

    const hasSlides = !!data.slideAnalysis;
    const hasRubric = !!data.rubricAnalysis;
    // --- Pagination Logic for Slides & Rubrics ---
    // Instead of chunking by 10/8 items, we strictly dedicate 1 whole page to Covered/Strengths
    // and 1 whole page to Missed/Weaknesses to prevent mid-page flexbox stretching issues.

    const hasSlideCovered = hasSlides && (data.slideAnalysis?.coveredPoints?.length || 0) > 0;
    const hasSlideMissed = hasSlides && (data.slideAnalysis?.missedPoints?.length || 0) > 0;

    const hasRubricStrengths = hasRubric && (data.rubricAnalysis?.strengths?.length || 0) > 0;
    const hasRubricWeaknesses = hasRubric && (data.rubricAnalysis?.weaknesses?.length || 0) > 0;

    let currentPageCounter = 7;

    const slideCoveredPageNum = hasSlideCovered ? ++currentPageCounter : -1;
    const slideMissedPageNum = hasSlideMissed ? ++currentPageCounter : -1;

    const rubricStrengthsPageNum = hasRubricStrengths ? ++currentPageCounter : -1;
    const rubricWeaknessesPageNum = hasRubricWeaknesses ? ++currentPageCounter : -1;

    const transcriptStartPage = currentPageCounter + 1;
    currentPageCounter += transcriptChunks.length;

    const analysisOrQnAStartPage = currentPageCounter + 1;
    currentPageCounter += hasQnA ? qnaChunks.length : analysisChunks.length;

    const pageNumTotal = currentPageCounter;

    return (
        <div id="printable-root">
            {/* PAGE 1: Summary, Metrics, Filler Words */}
            <PrintablePage pageNum={1} totalPages={pageNumTotal}>
                <h2 className="text-2xl font-bold text-slate-900 mb-6 border-b border-slate-200 pb-2 flex items-center gap-2">
                    <Activity className="w-6 h-6 text-blue-600" /> General Report
                </h2>

                {/* Executive Summary */}
                <div className="bg-slate-50 rounded-xl p-6 border border-slate-200 mb-8 flex items-center justify-between gap-8 shadow-sm">
                    <div className="flex-1">
                        <h3 className="text-xs font-bold text-blue-700 uppercase tracking-widest mb-3">Executive Summary</h3>
                        <p className="text-sm text-slate-700 leading-relaxed italic">"{data.summary}"</p>
                    </div>
                    {data.score !== undefined && (
                        <div className="flex-shrink-0">
                            <CircularScoreChart score={data.score} label="Overall Score" color="text-blue-600" size={120} strokeWidth={10} />
                        </div>
                    )}
                </div>

                {/* Key Metrics Grid */}
                <div className="grid grid-cols-4 gap-4 mb-8">
                    {/* WPM */}
                    <div className="p-4 rounded-xl border border-slate-200 bg-white shadow-sm">
                        <div className="flex items-center gap-2 text-slate-500 mb-2">
                            <Clock className="w-5 h-5" /> <span className="text-xs font-bold uppercase">Pace</span>
                        </div>
                        <div className="text-3xl font-bold text-slate-900 mb-1">{metrics.wpm} <span className="text-sm font-medium text-slate-500">WPM</span></div>
                        <div className={`text-sm font-medium ${getWpmColor(metrics.wpm)}`}>
                            {metrics.wpm < 110 ? "Slow" : metrics.wpm > 160 ? "Fast" : "Optimal"}
                        </div>
                    </div>
                    <div className="p-4 rounded-xl border border-slate-200 bg-white shadow-sm">
                        <div className="flex items-center gap-2 text-slate-500 mb-2">
                            <TrendingUp className="w-5 h-5" /> <span className="text-xs font-bold uppercase">Words</span>
                        </div>
                        <div className="text-3xl font-bold text-slate-900 mb-1">{metrics.totalWords}</div>
                        <div className="text-sm text-slate-500">
                            {Math.floor(metrics.duration / 60)}m {Math.floor(metrics.duration % 60)}s
                        </div>
                    </div>
                    {/* Fillers */}
                    <div className={`p-4 rounded-xl border bg-white shadow-sm ${fillerTotal > 5 ? 'border-red-200 bg-red-50' : 'border-slate-200'}`}>
                        <div className="flex items-center gap-2 text-slate-500 mb-2">
                            <AlertCircle className="w-5 h-5" /> <span className="text-xs font-bold uppercase">Fillers</span>
                        </div>
                        <div className={`text-3xl font-bold mb-1 ${fillerTotal > 5 ? 'text-red-700' : 'text-green-700'}`}>{fillerTotal}</div>
                    </div>
                    {/* Pauses */}
                    <div className="p-4 rounded-xl border border-slate-200 bg-white shadow-sm">
                        <div className="flex items-center gap-2 text-slate-500 mb-2">
                            <Mic className="w-5 h-5" /> <span className="text-xs font-bold uppercase">Pauses</span>
                        </div>
                        <div className="text-3xl font-bold text-slate-900">{metrics.pauseStats?.stats?.totalPauses || 0}</div>
                    </div>
                </div>

                {/* Filler Words Breakdown */}
                <div className="mb-4 p-6 rounded-2xl border border-slate-200 bg-slate-50 shadow-sm">
                    <h4 className="text-sm font-bold text-slate-900 mb-4 border-b border-slate-200 pb-2 flex items-center gap-2">
                        <AlertCircle className="w-5 h-5 text-slate-500" /> Filler Word Breakdown
                    </h4>
                    <div className="space-y-3">
                        {Object.entries(metrics.fillerCounts || {}).map(([word, count]) => (
                            <div key={word} className="flex items-center justify-between text-sm">
                                <span className="capitalize text-slate-700 font-medium">{word}</span>
                                <div className="flex items-center gap-3 flex-1 mx-4">
                                    <div className="h-2 bg-slate-200 rounded-full flex-1 overflow-hidden">
                                        <div
                                            className="h-full bg-slate-500 rounded-full"
                                            style={{ width: `${Math.min(((count as number) / Math.max(fillerTotal, 1)) * 100, 100)}%` }}
                                        />
                                    </div>
                                    <span className="font-mono font-bold text-slate-900">{count as number}</span>
                                </div>
                            </div>
                        ))}
                        {fillerTotal === 0 && <div className="text-sm text-slate-500 italic">No filler words detected.</div>}
                    </div>
                </div>
            </PrintablePage>

            {/* PAGE 2: General Recommendations */}
            <PrintablePage pageNum={2} totalPages={pageNumTotal}>
                <h2 className="text-2xl font-bold text-slate-900 mb-6 border-b border-slate-200 pb-2 flex items-center gap-2">
                    <Activity className="w-6 h-6 text-blue-600" /> General Recommendations
                </h2>

                <div className="flex-1 mt-4">
                    <h4 className="text-lg font-bold text-slate-900 mb-6 flex items-center gap-3 pb-3 border-b border-slate-200">
                        <span>💡</span> General Coach's Feedback
                    </h4>
                    <ul className="space-y-4">
                        {data.tips.map((tip: string, index: number) => (
                            <li key={index} className="flex gap-4 items-start text-[15px] text-slate-700 p-5 bg-white rounded-xl border border-slate-200 shadow-sm">
                                <span className="w-8 h-8 rounded-full bg-blue-600 text-white flex items-center justify-center text-sm font-bold shrink-0 shadow-sm">
                                    {index + 1}
                                </span>
                                <div className="leading-relaxed mt-1">{tip}</div>
                            </li>
                        ))}
                    </ul>
                </div>
            </PrintablePage>

            {/* PAGE 3: Vocal Analysis */}
            <PrintablePage pageNum={3} totalPages={pageNumTotal}>
                <h2 className="text-2xl font-bold text-slate-900 mb-6 border-b border-slate-200 pb-2 flex items-center gap-2">
                    <Mic className="w-6 h-6 text-pink-600" /> Vocal Analysis
                </h2>

                {/* Vocal Summary & Score */}
                {data.vocalSummary && (
                    <div className="bg-slate-50 rounded-xl p-6 border border-slate-200 mb-8 flex items-center justify-between gap-8 shadow-sm">
                        <div className="flex-1">
                            <h3 className="text-xs font-bold text-pink-700 uppercase tracking-widest mb-3">Vocal Coach Summary</h3>
                            <p className="text-[15px] text-slate-700 leading-relaxed italic">"{data.vocalSummary.summary}"</p>
                        </div>
                        {data.vocalSummary.score !== undefined && (
                            <div className="flex-shrink-0">
                                <CircularScoreChart score={data.vocalSummary.score} label="Vocal Score" color="text-pink-600" size={120} strokeWidth={10} />
                            </div>
                        )}
                    </div>
                )}

                {/* Vocal Recommendations */}
                {data.vocalSummary?.tips && data.vocalSummary.tips.length > 0 && (
                    <div className="mb-8">
                        <h4 className="text-[15px] font-bold text-slate-900 mb-4 flex items-center gap-3">
                            <span>💡</span> Vocal Pitch & Tone Recommendations
                        </h4>
                        <ul className="space-y-4">
                            {data.vocalSummary.tips.map((tip: string, index: number) => (
                                <li key={index} className="flex gap-4 items-start text-[14px] text-slate-700 p-4 bg-white rounded-xl border border-slate-200 shadow-sm">
                                    <span className="w-8 h-8 rounded-full bg-pink-100 text-pink-700 flex items-center justify-center text-sm font-bold shrink-0">
                                        {index + 1}
                                    </span>
                                    <div className="leading-relaxed mt-1">{tip}</div>
                                </li>
                            ))}
                        </ul>
                    </div>
                )}
            </PrintablePage>

            {/* PAGE 4: Vocal Dynamics & Pauses */}
            <PrintablePage pageNum={4} totalPages={pageNumTotal}>
                <h2 className="text-2xl font-bold text-slate-900 mb-6 border-b border-slate-200 pb-2 flex items-center gap-2">
                    <Mic className="w-6 h-6 text-pink-600" /> Vocal Dynamics & Pacing
                </h2>

                {/* Vocal Dynamics (Charts & Stats) */}
                <div className="mb-8 p-6 rounded-2xl border border-slate-200 bg-slate-50 shadow-sm">
                    <h3 className="text-sm font-bold text-slate-900 uppercase tracking-widest mb-4 flex items-center justify-between border-b border-slate-200 pb-3">
                        <div className="flex items-center gap-2"><Mic className="w-5 h-5 text-slate-500" /> Vocal Dynamics</div>
                    </h3>
                    <div className="grid grid-cols-3 gap-6 mb-4">
                        {audioStats && audioStats.stats && (
                            <>
                                <div className="p-4 bg-white rounded-xl border border-slate-200 text-center shadow-sm">
                                    <div className="text-sm text-slate-500 mb-2">Pitch Variety</div>
                                    <div className="text-2xl font-bold text-slate-900">{audioStats.stats.pitchStdDev?.toFixed(1) || 0}</div>
                                </div>
                                <div className="p-4 bg-white rounded-xl border border-slate-200 text-center shadow-sm">
                                    <div className="text-sm text-slate-500 mb-2">Clarity</div>
                                    <div className="text-2xl font-bold text-slate-900">{Math.round((1 - (audioStats.stats.quietPercentage || 0)) * 100)}%</div>
                                </div>
                                <div className={`p-4 bg-white rounded-xl border border-slate-200 text-center shadow-sm flex items-center justify-center font-bold text-xl ${audioStats.stats.isMonotone ? 'text-amber-600' : 'text-green-600'}`}>
                                    {audioStats.stats.isMonotone ? "Monotone" : "Expressive"}
                                </div>
                            </>
                        )}
                    </div>
                    <div className="p-4 rounded-xl bg-slate-900 border border-slate-800">
                        <div className="text-xs text-slate-400 mb-2 font-bold uppercase tracking-wider">Pitch Contour (Intonation)</div>
                        <div className="h-40 w-full relative">
                            <PitchChart pitchData={metrics.pitchSamples || []} volumeData={metrics.volumeSamples || []} color="#fbbf24" />
                        </div>
                    </div>
                </div>

                {/* Pause Analysis */}
                <div className="flex-1 p-6 rounded-2xl border border-slate-200 bg-slate-50 shadow-sm min-h-0">
                    <h3 className="text-sm font-bold text-slate-900 uppercase tracking-widest mb-4 flex items-center gap-2 border-b border-slate-200 pb-3">
                        <Clock className="w-5 h-5 text-slate-500" /> Pause Analysis
                    </h3>
                    {metrics.pauseStats && metrics.pauseStats.stats ? (
                        <div className="space-y-4">
                            <div className="grid grid-cols-2 gap-6">
                                <div className="p-5 rounded-xl bg-white border border-slate-200 text-center shadow-sm">
                                    <div className="text-4xl font-bold text-slate-900 mb-2">{metrics.pauseStats.stats.emphasisCount}</div>
                                    <div className="text-sm text-slate-500">Emphasis Pauses</div>
                                    <div className="mt-4 h-2 w-full bg-slate-100 rounded-full overflow-hidden">
                                        <div className="h-full bg-emerald-500" style={{ width: `${(metrics.pauseStats.stats.emphasisCount / Math.max(metrics.pauseStats.stats.totalPauses, 1)) * 100}%` }} />
                                    </div>
                                </div>
                                <div className="p-5 rounded-xl bg-white border border-slate-200 text-center shadow-sm">
                                    <div className="text-4xl font-bold text-amber-600 mb-2">{metrics.pauseStats.stats.thinkingCount}</div>
                                    <div className="text-sm text-slate-500">Thinking Pauses</div>
                                    <div className="mt-4 h-2 w-full bg-slate-100 rounded-full overflow-hidden">
                                        <div className="h-full bg-amber-500" style={{ width: `${(metrics.pauseStats.stats.thinkingCount / Math.max(metrics.pauseStats.stats.totalPauses, 1)) * 100}%` }} />
                                    </div>
                                </div>
                            </div>
                            {metrics.pauseStats.feedback && (
                                <div className="p-5 rounded-xl border bg-white shadow-sm flex items-start gap-4">
                                    <div className="text-3xl">{metrics.pauseStats.feedback.type === 'good' ? '✅' : metrics.pauseStats.feedback.type === 'warn' ? '⚠️' : '🚨'}</div>
                                    <div className="mt-1">
                                        <div className="text-[15px] font-bold text-slate-900 mb-1">Pacing Feedback</div>
                                        <div className="text-[14px] text-slate-700 leading-relaxed">{metrics.pauseStats.feedback.message}</div>
                                    </div>
                                </div>
                            )}
                        </div>
                    ) : (
                        <em className="text-slate-400 text-sm">No pause tracking available.</em>
                    )}
                </div>
            </PrintablePage>

            {/* PAGE 5: Posture Analysis */}
            <PrintablePage pageNum={5} totalPages={pageNumTotal}>
                <h2 className="text-2xl font-bold text-slate-900 mb-6 border-b border-slate-200 pb-2 flex items-center gap-2">
                    <Activity className="w-6 h-6 text-cyan-600" /> Posture & Presence
                </h2>

                {/* Posture Summary & Score */}
                {data.postureSummary && (
                    <div className="bg-slate-50 rounded-xl p-6 border border-slate-200 mb-6 flex items-center justify-between gap-8 shadow-sm">
                        <div className="flex-1">
                            <h3 className="text-xs font-bold text-cyan-700 uppercase tracking-widest mb-3">Body Language Coach</h3>
                            <p className="text-[15px] text-slate-700 leading-relaxed italic">"{data.postureSummary.summary}"</p>
                        </div>
                        {data.postureSummary.score !== undefined && (
                            <div className="flex-shrink-0">
                                <CircularScoreChart score={data.postureSummary.score} label="Posture Score" color="text-cyan-600" size={120} strokeWidth={10} />
                            </div>
                        )}
                    </div>
                )}

                {/* Posture Recommendations */}
                {data.postureSummary?.tips && data.postureSummary.tips.length > 0 && (
                    <div className="flex-1 mb-8">
                        <h4 className="text-[15px] font-bold text-slate-900 mb-4 flex items-center gap-2">
                            <span>💡</span> Posture Recommendations
                        </h4>
                        <ul className="space-y-4">
                            {data.postureSummary.tips.map((tip: string, index: number) => (
                                <li key={index} className="flex gap-4 items-start text-[14px] text-slate-700 p-4 bg-white rounded-xl border border-slate-200 shadow-sm">
                                    <span className="w-8 h-8 rounded-full bg-cyan-100 text-cyan-700 flex items-center justify-center text-sm font-bold shrink-0">
                                        {index + 1}
                                    </span>
                                    <div className="leading-relaxed mt-1">{tip}</div>
                                </li>
                            ))}
                        </ul>
                    </div>
                )}
            </PrintablePage>

            {/* PAGE 6: Detailed Posture Issues */}
            <PrintablePage pageNum={6} totalPages={pageNumTotal}>
                <h2 className="text-2xl font-bold text-slate-900 mb-6 border-b border-slate-200 pb-2 flex items-center gap-2">
                    <Activity className="w-6 h-6 text-cyan-600" /> Posture Deviations
                </h2>

                {/* Detected Posture Issues */}
                <div className="flex-1 p-6 rounded-2xl border border-slate-200 bg-slate-50 shadow-sm min-h-0">
                    <h3 className="text-sm font-bold text-slate-900 uppercase tracking-widest mb-4 flex items-center gap-2 border-b border-slate-200 pb-3">
                        <AlertTriangle className="w-5 h-5 text-red-500" /> Detected Posture Issues
                    </h3>
                    {metrics.issueCounts && Object.keys(metrics.issueCounts).length > 0 ? (
                        <div className="space-y-4">
                            {Object.entries(metrics.issueCounts).map(([issue, count]) => (
                                <div key={issue} className="flex items-center justify-between group p-4 bg-white rounded-xl border border-slate-200 shadow-sm">
                                    <span className="text-slate-800 text-base font-bold capitalize">{issue.replace(/_/g, ' ').toLowerCase()}</span>
                                    <span className="flex items-center gap-3">
                                        <span className="text-xs font-bold text-slate-500 uppercase">Count</span>
                                        <span className="w-10 h-10 rounded-full bg-red-100 text-red-700 flex items-center justify-center font-bold text-sm border border-red-200">
                                            {count as number}
                                        </span>
                                    </span>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <em className="text-slate-400 text-sm">No significant posture deviations detected. Great form!</em>
                    )}
                </div>
            </PrintablePage>

            {/* PAGE 7: Content Analysis OR Q&A Summary */}
            <PrintablePage pageNum={7} totalPages={pageNumTotal}>
                {hasQnA ? (
                    <>
                        <h2 className="text-2xl font-bold text-slate-900 mb-6 border-b border-slate-200 pb-2 flex items-center gap-2">
                            <Target className="w-6 h-6 text-teal-600" /> Q&A Session Overview
                        </h2>

                        <div className="bg-slate-50 rounded-xl p-6 border border-slate-200 mb-8 flex items-center justify-between gap-8 shadow-sm">
                            <div className="flex-1">
                                <h3 className="text-xs font-bold text-teal-700 uppercase tracking-widest mb-3">Q&A Relevance Summary</h3>
                                <p className="text-slate-700 text-[15px] leading-relaxed">
                                    This score represents how well your responses addressed the specific questions asked during the Q&A session.
                                </p>
                            </div>
                            <div className="flex-shrink-0">
                                <CircularScoreChart
                                    score={Math.round(data.qnaSummary.reduce((a: number, c: any) => a + c.relevanceScore, 0) / Math.max(1, data.qnaSummary.length))}
                                    label="Avg Relevance" color="text-teal-600" size={120} strokeWidth={10}
                                />
                            </div>
                        </div>

                        <div className="mb-6 p-6 rounded-2xl border border-slate-200 bg-slate-50 shadow-sm">
                            <h3 className="text-sm font-bold text-slate-900 uppercase tracking-widest mb-4 flex items-center gap-2 border-b border-slate-200 pb-3">
                                <Activity className="w-5 h-5 text-slate-500" /> Delivery Pacing
                            </h3>
                            <div className="p-4 rounded-xl bg-slate-900 border border-slate-800">
                                <div className="text-xs text-slate-400 mb-3 font-bold uppercase tracking-wider">WPM Trend over Q&A</div>
                                <div className="h-48 w-full relative">
                                    <PacingChart
                                        dataPoints={
                                            pacingBuckets.length > 0
                                                ? pacingBuckets.map((b: any) => ({ time: b.time, wpm: b.wpm, wordCount: b.wordCount }))
                                                : [{ time: 0, wpm: metrics.wpm, wordCount: 0 }, { time: metrics.duration, wpm: metrics.wpm, wordCount: 0 }]
                                        }
                                    />
                                </div>
                            </div>
                        </div>
                    </>
                ) : (
                    <>
                        <h2 className="text-2xl font-bold text-slate-900 mb-6 border-b border-slate-200 pb-2 flex items-center gap-2">
                            <BarChart3 className="w-6 h-6 text-green-600" /> Content & Script Analysis
                        </h2>

                        {/* Content Score Summary */}
                        <div className="bg-slate-50 rounded-xl p-6 border border-slate-200 mb-8 flex items-center justify-between gap-8 shadow-sm">
                            <div className="flex-1">
                                <h3 className="text-xs font-bold text-green-700 uppercase tracking-widest mb-3">Content Heuristic Evaluation</h3>
                                <p className="text-slate-700 text-[15px] leading-relaxed">
                                    Score calculated locally based on your transcript length, pacing dynamics, and filler word frequency.
                                </p>
                            </div>
                            {localContentScore !== undefined && (
                                <div className="flex-shrink-0">
                                    <CircularScoreChart score={localContentScore} label="Content Score" color="text-green-600" size={120} strokeWidth={10} />
                                </div>
                            )}
                        </div>

                        {/* Pacing Chart */}
                        <div className="mb-6 p-6 rounded-2xl border border-slate-200 bg-slate-50 shadow-sm">
                            <h3 className="text-sm font-bold text-slate-900 uppercase tracking-widest mb-4 flex items-center gap-2 border-b border-slate-200 pb-3">
                                <Activity className="w-5 h-5 text-slate-500" /> Pacing Analysis
                            </h3>
                            <div className="p-4 rounded-xl bg-slate-900 border border-slate-800">
                                <div className="text-xs text-slate-400 mb-3 font-bold uppercase tracking-wider">WPM Trend</div>
                                <div className="h-48 w-full relative">
                                    <PacingChart
                                        dataPoints={
                                            pacingBuckets.length > 0
                                                ? pacingBuckets.map((b: any) => ({ time: b.time, wpm: b.wpm, wordCount: b.wordCount }))
                                                : [{ time: 0, wpm: metrics.wpm, wordCount: 0 }, { time: metrics.duration, wpm: metrics.wpm, wordCount: 0 }]
                                        }
                                    />
                                </div>
                            </div>
                        </div>
                    </>
                )}
            </PrintablePage>

            {/* PAGE X: Slide Alignment - Covered Points */}
            {hasSlideCovered && (
                <PrintablePage pageNum={slideCoveredPageNum} totalPages={pageNumTotal}>
                    <h2 className="text-2xl font-bold text-slate-900 mb-6 border-b border-slate-200 pb-2 flex items-center gap-2">
                        <FileText className="w-6 h-6 text-blue-600" /> Slide Alignment
                    </h2>

                    <div className="bg-slate-50 rounded-xl p-6 border border-slate-200 mb-8 flex items-center justify-between gap-8 shadow-sm">
                        <div className="flex-1">
                            <h3 className="text-xs font-bold text-blue-700 uppercase tracking-widest mb-3">Slide Alignment Summary</h3>
                            <p className="text-slate-700 text-[15px] leading-relaxed italic">
                                "{data.slideAnalysis!.feedback}"
                            </p>
                        </div>
                        {data.slideAnalysis!.alignmentScore !== undefined && (
                            <div className="flex-shrink-0">
                                <CircularScoreChart score={data.slideAnalysis!.alignmentScore} label="Alignment" color="text-blue-600" size={120} strokeWidth={10} />
                            </div>
                        )}
                    </div>

                    <div className="flex-1 p-6 rounded-2xl border border-slate-200 bg-green-50/50 shadow-sm flex flex-col min-h-0 bg-white">
                        <h3 className="text-sm font-bold text-green-700 uppercase tracking-widest mb-4 flex items-center gap-2 border-b border-green-200 pb-2 flex-shrink-0">
                            ✅ Points Covered
                        </h3>
                        <ul className="space-y-3 overflow-y-auto pr-2 pb-2">
                            {data.slideAnalysis!.coveredPoints.map((point: string, i: number) => (
                                <li key={i} className="flex items-start gap-3 p-3 bg-white rounded-xl border border-green-100 shadow-sm shrink-0">
                                    <span className="flex-shrink-0 w-6 h-6 rounded-full bg-green-100 text-green-600 flex items-center justify-center font-bold text-xs">✓</span>
                                    <p className="text-[14px] text-slate-700 leading-snug pt-0.5">{point}</p>
                                </li>
                            ))}
                        </ul>
                    </div>
                </PrintablePage>
            )}

            {/* PAGE Y: Slide Alignment - Missed Points */}
            {hasSlideMissed && (
                <PrintablePage pageNum={slideMissedPageNum} totalPages={pageNumTotal}>
                    <h2 className="text-2xl font-bold text-slate-900 mb-6 border-b border-slate-200 pb-2 flex items-center gap-2">
                        <FileText className="w-6 h-6 text-blue-600" /> Slide Alignment (Continued)
                    </h2>

                    <div className="flex-1 p-6 rounded-2xl border border-slate-200 bg-amber-50/50 shadow-sm flex flex-col min-h-0">
                        <h3 className="text-sm font-bold text-amber-700 uppercase tracking-widest mb-4 flex items-center gap-2 border-b border-amber-200 pb-2 flex-shrink-0">
                            ⚠️ Missed Points
                        </h3>
                        <ul className="space-y-3 overflow-y-auto pr-2 pb-2">
                            {data.slideAnalysis!.missedPoints.map((point: string, i: number) => (
                                <li key={i} className="flex items-start gap-3 p-3 bg-white rounded-xl border border-amber-100 shadow-sm shrink-0">
                                    <span className="flex-shrink-0 w-6 h-6 rounded-full bg-amber-100 text-amber-600 flex items-center justify-center font-bold text-xs">!</span>
                                    <p className="text-[14px] text-slate-700 leading-snug pt-0.5">{point}</p>
                                </li>
                            ))}
                        </ul>
                    </div>
                </PrintablePage>
            )}

            {/* PAGE W: Rubric Evaluation - Strengths */}
            {hasRubricStrengths && (
                <PrintablePage pageNum={rubricStrengthsPageNum} totalPages={pageNumTotal}>
                    <h2 className="text-2xl font-bold text-slate-900 mb-6 border-b border-slate-200 pb-2 flex items-center gap-2">
                        <AlertCircle className="w-6 h-6 text-purple-600" /> Rubric Evaluation
                    </h2>

                    <div className="bg-slate-50 rounded-xl p-6 border border-slate-200 mb-8 flex items-center justify-between gap-8 shadow-sm">
                        <div className="flex-1">
                            <h3 className="text-xs font-bold text-purple-700 uppercase tracking-widest mb-3">Rubric Summary</h3>
                            <p className="text-slate-700 text-[15px] leading-relaxed italic">
                                "{data.rubricAnalysis!.feedback}"
                            </p>
                        </div>
                        {data.rubricAnalysis!.rubricScore !== undefined && (
                            <div className="flex-shrink-0">
                                <CircularScoreChart score={data.rubricAnalysis!.rubricScore} label="Rubric Score" color="text-purple-600" size={120} strokeWidth={10} />
                            </div>
                        )}
                    </div>

                    <div className="flex-1 p-6 rounded-2xl border border-slate-200 bg-purple-50/50 shadow-sm flex flex-col min-h-0 bg-white">
                        <h3 className="text-sm font-bold text-purple-700 uppercase tracking-widest mb-4 flex items-center gap-2 border-b border-purple-200 pb-2 flex-shrink-0">
                            🌟 Key Strengths
                        </h3>
                        <ul className="space-y-3 overflow-y-auto pr-2 pb-2">
                            {data.rubricAnalysis!.strengths.map((strength: string, i: number) => (
                                <li key={i} className="flex items-start gap-3 p-3 bg-white rounded-xl border border-purple-100 shadow-sm shrink-0">
                                    <span className="flex-shrink-0 w-6 h-6 rounded-full bg-purple-100 text-purple-600 flex items-center justify-center font-bold text-xs">↑</span>
                                    <p className="text-[14px] text-slate-700 leading-snug pt-0.5">{strength}</p>
                                </li>
                            ))}
                        </ul>
                    </div>
                </PrintablePage>
            )}

            {/* PAGE Z: Rubric Evaluation - Weaknesses */}
            {hasRubricWeaknesses && (
                <PrintablePage pageNum={rubricWeaknessesPageNum} totalPages={pageNumTotal}>
                    <h2 className="text-2xl font-bold text-slate-900 mb-6 border-b border-slate-200 pb-2 flex items-center gap-2">
                        <AlertCircle className="w-6 h-6 text-purple-600" /> Rubric Evaluation (Continued)
                    </h2>

                    <div className="flex-1 p-6 rounded-2xl border border-slate-200 bg-rose-50/50 shadow-sm flex flex-col min-h-0">
                        <h3 className="text-sm font-bold text-rose-700 uppercase tracking-widest mb-4 flex items-center gap-2 border-b border-rose-200 pb-2 flex-shrink-0">
                            🎯 Areas to Improve
                        </h3>
                        <ul className="space-y-3 overflow-y-auto pr-2 pb-2">
                            {data.rubricAnalysis!.weaknesses.map((weakness: string, i: number) => (
                                <li key={i} className="flex items-start gap-3 p-3 bg-white rounded-xl border border-rose-100 shadow-sm shrink-0">
                                    <span className="flex-shrink-0 w-6 h-6 rounded-full bg-rose-100 text-rose-600 flex items-center justify-center font-bold text-xs">↓</span>
                                    <p className="text-[14px] text-slate-700 leading-snug pt-0.5">{weakness}</p>
                                </li>
                            ))}
                        </ul>
                    </div>
                </PrintablePage>
            )}

            {/* PAGE 8+: Transcript Elements */}

            {transcriptChunks.map((chunk, index) => (
                <PrintablePage key={`chunk-${index}`} pageNum={transcriptStartPage + index} totalPages={pageNumTotal}>
                    <div className="flex-1 flex flex-col min-h-0 mb-6">
                        <h3 className="text-sm font-bold text-slate-900 uppercase tracking-widest mb-4 flex items-center gap-2 border-b border-slate-200 pb-3">
                            <Mic className="w-5 h-5 text-slate-500" /> Full Transcript {index > 0 ? "(Continued)" : ""}
                        </h3>
                        <div className="flex-1 bg-slate-50 rounded-2xl p-8 border border-slate-200 text-base leading-relaxed text-slate-700 whitespace-pre-wrap font-serif overflow-hidden">
                            {chunk ? chunk : <em className="text-slate-400">No transcript available for this session.</em>}
                        </div>
                    </div>
                </PrintablePage>
            ))}

            {/* PAGE 8+n: AI Content Coach Analysis OR Q&A Breakdown */}
            {hasQnA ? (
                qnaChunks.map((chunk, chunkIndex) => (
                    <PrintablePage key={`qna-${chunkIndex}`} pageNum={analysisOrQnAStartPage + chunkIndex} totalPages={pageNumTotal}>
                        <div className="mb-6">
                            <h3 className="text-sm font-bold text-slate-900 uppercase tracking-widest mb-6 flex items-center gap-2 border-b border-slate-200 pb-3">
                                <MessageSquareText className="w-5 h-5 text-teal-600" /> Q&A Breakdown {chunkIndex > 0 ? "(Continued)" : ""}
                            </h3>
                            <div className="space-y-6">
                                {chunk.map((qna: any, idx: number) => {
                                    const questionNum = chunkIndex + 1;
                                    return (
                                        <div key={idx} className="bg-slate-50 rounded-2xl p-6 border border-slate-200 shadow-sm shrink-0 page-break-inside-avoid">
                                            <div className="flex items-start justify-between gap-4 mb-4">
                                                <div>
                                                    <div className="text-xs font-bold text-teal-700 uppercase tracking-widest mb-1 flex items-center gap-1">
                                                        <MessageSquareText className="w-3 h-3" /> Question {questionNum}
                                                    </div>
                                                    <h4 className="text-sm font-bold text-slate-900 leading-snug">{qna.question}</h4>
                                                </div>
                                                <div className="flex flex-col items-center justify-center bg-white rounded-xl border border-slate-200 p-2 min-w-[60px] shadow-sm shrink-0">
                                                    <span className="text-xl font-bold text-teal-600">{Math.round(qna.relevanceScore)}</span>
                                                    <span className="text-[9px] text-slate-500 uppercase tracking-wider font-bold">Score</span>
                                                </div>
                                            </div>
                                            <div className="grid grid-cols-2 gap-4">
                                                <div className="bg-white rounded-xl p-4 border border-slate-200 shadow-sm">
                                                    <div className="flex items-center gap-2 text-slate-500 text-[10px] font-bold uppercase tracking-widest mb-2">
                                                        <Mic className="w-3 h-3" /> Your Answer
                                                    </div>
                                                    <p className="text-slate-700 text-sm leading-relaxed whitespace-pre-wrap">{qna.userAnswer}</p>
                                                </div>
                                                <div className="bg-teal-50 rounded-xl p-4 border border-teal-100 shadow-sm">
                                                    <div className="flex items-center gap-2 text-teal-700 text-[10px] font-bold uppercase tracking-widest mb-2">
                                                        <Sparkles className="w-3 h-3" /> Ideal Answer Concept
                                                    </div>
                                                    <p className="text-teal-900 text-sm leading-relaxed whitespace-pre-wrap">{qna.idealAnswer}</p>
                                                </div>
                                            </div>
                                        </div>
                                    );
                                })}
                            </div>
                        </div>
                    </PrintablePage>
                ))
            ) : (
                analysisChunks.map((chunk, index) => (
                    <PrintablePage key={`analysis-${index}`} pageNum={analysisOrQnAStartPage + index} totalPages={pageNumTotal}>
                        <div className="flex-1 flex flex-col min-h-0 mb-6">
                            <h3 className="text-sm font-bold text-slate-900 uppercase tracking-widest mb-4 flex items-center gap-2 border-b border-slate-200 pb-3">
                                <Activity className="w-5 h-5 text-slate-500" /> AI Content Coach Findings {index > 0 ? "(Continued)" : ""}
                            </h3>
                            <div className="flex-1 bg-slate-50 rounded-2xl p-8 border border-slate-200 text-base leading-relaxed text-slate-700 font-serif overflow-hidden prose prose-base max-w-none break-inside-avoid shadow-inner prose-p:my-5 prose-li:my-2 prose-headings:mb-4 prose-headings:mt-6">
                                {chunk ? <ReactMarkdown>{chunk}</ReactMarkdown> : <em className="text-slate-400">Content analysis pending or unavailable.</em>}
                            </div>
                        </div>
                    </PrintablePage>
                ))
            )}
        </div>
    );
}
