import React from "react";
import { Activity, Clock, AlertCircle, Mic, TrendingUp, BarChart3, AlertTriangle } from "lucide-react";
import { PacingChart } from "./PacingChart";
import { PitchChart } from "@/components/PitchChart";

interface PrintableReportTemplateProps {
    data: any;
    metrics: any;
}

// Internal reusable page component to ensure consistent A4 sizing and header/footer
const PrintablePage = ({ children, pageNum, totalPages }: { children: React.ReactNode, pageNum: number, totalPages: number }) => {
    const [date, setDate] = React.useState<string>("");

    React.useEffect(() => {
        setDate(new Date().toLocaleDateString());
    }, []);

    return (
        <div className="printable-page w-[794px] h-[1123px] bg-white text-slate-900 p-12 font-sans relative flex flex-col mb-8 shadow-lg">
            {/* Header */}
            <div className="flex justify-between items-end border-b-2 border-slate-200 pb-6 mb-8 shrink-0">
                <div>
                    <h1 className="text-3xl font-bold text-slate-900 mb-1">Session Report</h1>
                    <p className="text-slate-500 text-sm">Generated by VoxLab AI Coach</p>
                </div>
                <div className="text-right">
                    <div className="text-sm font-bold text-slate-900">{date}</div>
                    <div className="text-xs text-slate-500">Page {pageNum} of {totalPages}</div>
                </div>
            </div>

            {/* Content Area - Grows to fill space */}
            <div className="flex-1 flex flex-col">
                {children}
            </div>

            {/* Footer */}
            <div className="mt-auto pt-6 border-t border-slate-200 text-center text-xs text-slate-400 shrink-0">
                VoxLab AI &bull; Private & Confidential &bull; Practice Session Analysis
            </div>
        </div>
    );
};

// Helper Component for consistency
const MetricCard = ({ title, icon: Icon, children, className = "" }: { title: string, icon: any, children: React.ReactNode, className?: string }) => (
    <div className={`p-6 rounded-2xl border border-slate-200 bg-slate-50 ${className}`}>
        <h3 className="text-sm font-bold text-slate-900 uppercase tracking-widest mb-6 flex items-center gap-2 border-b border-slate-200 pb-2">
            <Icon className="w-4 h-4 text-slate-500" /> {title}
        </h3>
        {children}
    </div>
);

export function PrintableReportTemplate({ data, metrics }: PrintableReportTemplateProps) {
    const fillerTotal = Object.values(metrics.fillerCounts || {}).reduce((a: any, b: any) => a + b, 0) as number;

    const getWpmColor = (wpm: number) => {
        if (wpm < 110 || wpm > 160) return "text-red-700";
        if (wpm < 130 || wpm > 155) return "text-amber-700";
        return "text-green-700";
    };

    // Calculate Pacing Buckets (Logic copied from DetailedSessionReport)
    const BUCKET_SIZE = 30;
    const words = metrics.words || [];
    const maxTime = Math.max(metrics.duration, ...(words.map((w: any) => w.endTime) || [0]), 1);
    const totalBuckets = Math.ceil(maxTime / BUCKET_SIZE);

    // Fallback if words are missing but history exists
    const pacingBuckets = words.length === 0 && Array.isArray(metrics.wpmHistory) && metrics.wpmHistory.length > 0
        ? [] // Legacy mode fallback not implemented for print to save space, relies on history chart
        : Array.from({ length: totalBuckets }, (_, i) => {
            const startTime = i * BUCKET_SIZE;
            const endTime = (i + 1) * BUCKET_SIZE;
            const bucketWords = words.filter((w: any) =>
                (w.startTime >= startTime && w.startTime < endTime) ||
                (w.endTime > startTime && w.endTime <= endTime)
            );
            const count = bucketWords.length;
            const wpm = Math.round((count / BUCKET_SIZE) * 60);
            let color = "bg-green-500";
            let textColor = "text-green-700";
            if (wpm < 110 || wpm > 155) { color = "bg-red-500"; textColor = "text-red-700"; }
            else if (wpm < 130 || wpm > 155) { color = "bg-amber-500"; textColor = "text-amber-700"; }
            return { intervalLabel: `${startTime}s – ${endTime}s`, wpm, wordCount: count, color, textColor, time: endTime };
        });

    const audioStats = metrics.audioMetrics ? {
        stats: {
            ...metrics.audioMetrics,
            pitchStdDev: metrics.audioMetrics.pitchStdDev ?? metrics.audioMetrics.pitchRange,
            quietPercentage: metrics.audioMetrics.quietPercentage ?? (metrics.audioMetrics.isTooQuiet ? 0.8 : 0.1)
        },
        feedback: {
            type: metrics.audioMetrics.isMonotone ? "warn" : "good",
            message: metrics.audioMetrics.isMonotone ? "Try varying your pitch more." : "Good tonal variety."
        }
    } : null;

    return (
        <div id="printable-root">
            {/* PAGE 1: Summary, Metrics, Filler Words */}
            <PrintablePage pageNum={1} totalPages={4}>
                {/* Executive Summary */}
                <div className="bg-slate-50 rounded-xl p-6 border border-slate-200 mb-8">
                    <h3 className="text-xs font-bold text-blue-700 uppercase tracking-widest mb-3 flex items-center gap-2">
                        <Activity className="w-4 h-4" /> Executive Summary
                    </h3>
                    <p className="text-slate-700 leading-relaxed italic">
                        "{data.summary}"
                    </p>
                </div>

                {/* Key Metrics Grid */}
                <div className="grid grid-cols-4 gap-4 mb-8">
                    {/* WPM */}
                    <div className="p-4 rounded-xl border border-slate-200 bg-white shadow-sm">
                        <div className="flex items-center gap-2 text-slate-500 mb-2">
                            <Clock className="w-4 h-4" /> <span className="text-[10px] font-bold uppercase">Pace</span>
                        </div>
                        <div className="text-2xl font-bold text-slate-900 mb-1">{metrics.wpm} <span className="text-sm font-medium text-slate-500">WPM</span></div>
                        <div className={`text-xs font-medium ${getWpmColor(metrics.wpm)}`}>
                            {metrics.wpm < 110 ? "Slow" : metrics.wpm > 160 ? "Fast" : "Optimal"}
                        </div>
                    </div>
                    {/* Total Words */}
                    <div className="p-4 rounded-xl border border-slate-200 bg-white shadow-sm">
                        <div className="flex items-center gap-2 text-slate-500 mb-2">
                            <TrendingUp className="w-4 h-4" /> <span className="text-[10px] font-bold uppercase">Words</span>
                        </div>
                        <div className="text-2xl font-bold text-slate-900 mb-1">{metrics.totalWords}</div>
                        <div className="text-xs text-slate-500">
                            {Math.floor(metrics.duration / 60)}m {Math.floor(metrics.duration % 60)}s
                        </div>
                    </div>
                    {/* Fillers */}
                    <div className={`p-4 rounded-xl border bg-white shadow-sm ${fillerTotal > 5 ? 'border-red-200 bg-red-50' : 'border-slate-200'}`}>
                        <div className="flex items-center gap-2 text-slate-500 mb-2">
                            <AlertCircle className="w-4 h-4" /> <span className="text-[10px] font-bold uppercase">Fillers</span>
                        </div>
                        <div className={`text-2xl font-bold mb-1 ${fillerTotal > 5 ? 'text-red-700' : 'text-green-700'}`}>{fillerTotal}</div>
                    </div>
                    {/* Pauses */}
                    <div className="p-4 rounded-xl border border-slate-200 bg-white shadow-sm">
                        <div className="flex items-center gap-2 text-slate-500 mb-2">
                            <Mic className="w-4 h-4" /> <span className="text-[10px] font-bold uppercase">Pauses</span>
                        </div>
                        <div className="text-2xl font-bold text-slate-900 mb-1">{metrics.pauseCount}</div>
                    </div>
                </div>

                {/* Filler Words & Stats */}
                <div className="mb-8 p-6 rounded-2xl border border-slate-200 bg-slate-50">
                    <h4 className="text-sm font-bold text-slate-900 mb-4 border-b border-slate-200 pb-2 flex items-center gap-2">
                        <AlertCircle className="w-4 h-4 text-slate-500" /> Filler Word Breakdown
                    </h4>
                    <div className="grid grid-cols-2 gap-8">
                        <div className="space-y-3">
                            {Object.entries(metrics.fillerCounts || {}).map(([word, count]) => (
                                <div key={word} className="flex items-center justify-between text-sm">
                                    <span className="capitalize text-slate-700 font-medium">{word}</span>
                                    <div className="flex items-center gap-3 flex-1 mx-4">
                                        <div className="h-2 bg-slate-200 rounded-full flex-1 overflow-hidden">
                                            <div
                                                className="h-full bg-slate-500 rounded-full"
                                                style={{ width: `${Math.min(((count as number) / Math.max(fillerTotal, 1)) * 100, 100)}%` }}
                                            />
                                        </div>
                                        <span className="font-mono font-bold text-slate-900">{count as number}</span>
                                    </div>
                                </div>
                            ))}
                            {fillerTotal === 0 && <div className="text-sm text-slate-500 italic">No filler words detected.</div>}
                        </div>
                        {/* Audio Stats Mini-Table */}
                        {audioStats && (
                            <div className="grid grid-cols-2 gap-4">
                                <div className="p-3 bg-white rounded-lg border border-slate-200 text-center">
                                    <div className="text-sm text-slate-500 mb-1">Pitch Variety</div>
                                    <div className="text-xl font-bold text-slate-900">{audioStats.stats.pitchStdDev?.toFixed(1) || 0}</div>
                                </div>
                                <div className="p-3 bg-white rounded-lg border border-slate-200 text-center">
                                    <div className="text-sm text-slate-500 mb-1">Clarity</div>
                                    <div className="text-xl font-bold text-slate-900">{Math.round((1 - (audioStats.stats.quietPercentage || 0)) * 100)}%</div>
                                </div>
                            </div>
                        )}
                    </div>
                </div>

                {/* Pause Analysis (High Fidelity) */}
                <MetricCard title="Pause Analysis" icon={Clock}>
                    {metrics.pauseStats && metrics.pauseStats.stats ? (
                        <div className="space-y-6">
                            <div className="grid grid-cols-2 gap-4">
                                <div className="p-3 rounded-xl bg-white border border-slate-200 text-center shadow-sm">
                                    <div className="text-2xl font-bold text-slate-900">{metrics.pauseStats.stats.emphasisCount}</div>
                                    <div className="text-xs text-slate-500">Emphasis Pauses</div>
                                    <div className="mt-2 h-1 w-full bg-slate-100 rounded-full overflow-hidden">
                                        <div className="h-full bg-emerald-500" style={{ width: `${(metrics.pauseStats.stats.emphasisCount / Math.max(metrics.pauseStats.stats.totalPauses, 1)) * 100}%` }} />
                                    </div>
                                </div>
                                <div className="p-3 rounded-xl bg-white border border-slate-200 text-center shadow-sm">
                                    <div className="text-2xl font-bold text-amber-600">{metrics.pauseStats.stats.thinkingCount}</div>
                                    <div className="text-xs text-slate-500">Thinking Pauses</div>
                                    <div className="mt-2 h-1 w-full bg-slate-100 rounded-full overflow-hidden">
                                        <div className="h-full bg-amber-500" style={{ width: `${(metrics.pauseStats.stats.thinkingCount / Math.max(metrics.pauseStats.stats.totalPauses, 1)) * 100}%` }} />
                                    </div>
                                </div>
                            </div>
                            {metrics.pauseStats.feedback && (
                                <div className={`p-4 rounded-xl border text-sm flex items-start gap-3 ${metrics.pauseStats.feedback.type === 'good' ? 'bg-green-50 border-green-200 text-green-800' : 'bg-amber-50 border-amber-200 text-amber-800'}`}>
                                    <AlertTriangle className="w-4 h-4 mt-0.5 shrink-0" />
                                    <div>
                                        <div className="font-bold mb-1">Feedback</div>
                                        {metrics.pauseStats.feedback.message}
                                    </div>
                                </div>
                            )}
                        </div>
                    ) : <div className="text-sm text-slate-400 italic">No pause data available.</div>}
                </MetricCard>
            </PrintablePage>

            {/* PAGE 2: Deep Analysis (Pacing & Dynamics) */}
            <PrintablePage pageNum={2} totalPages={4}>
                <h2 className="text-xl font-bold text-slate-900 mb-6">Deep Analysis</h2>

                {/* Vocal Dynamics (Charts) */}
                <div className="mb-8 p-6 rounded-2xl border border-slate-200 bg-slate-50">
                    <h3 className="text-sm font-bold text-slate-900 uppercase tracking-widest mb-6 flex items-center gap-2 border-b border-slate-200 pb-2">
                        <Mic className="w-4 h-4 text-slate-500" /> Vocal Dynamics
                    </h3>
                    {/* Pitch Wave Graph - Wrapped in dark container to preserve chart contrast/visibility as requested by user logic to match screen */}
                    <div className="p-4 rounded-xl bg-slate-900 border border-slate-800">
                        <div className="text-xs text-slate-400 mb-4 font-bold uppercase tracking-wider">Pitch Contour (Intonation)</div>
                        <div className="h-48 w-full">
                            <PitchChart
                                pitchData={metrics.pitchSamples || []}
                                volumeData={metrics.volumeSamples || []}
                                color="#fbbf24"
                            />
                        </div>
                    </div>
                </div>

                {/* Pacing Over Time */}
                <div className="mb-8 p-6 rounded-2xl border border-slate-200 bg-slate-50">
                    <h3 className="text-sm font-bold text-slate-900 uppercase tracking-widest mb-6 flex items-center gap-2 border-b border-slate-200 pb-2">
                        <Activity className="w-4 h-4 text-slate-500" /> Pacing Analysis
                    </h3>

                    {/* Chart - Dark Container */}
                    <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 mb-6">
                        <div className="text-xs text-slate-400 mb-4 font-bold uppercase tracking-wider">WPM Trend (30s Intervals)</div>
                        <div className="h-48 w-full">
                            <PacingChart
                                dataPoints={
                                    pacingBuckets.length > 0
                                        ? pacingBuckets.map(b => ({ time: b.time, wpm: b.wpm, wordCount: b.wordCount }))
                                        : (metrics.wpmHistory || []).map((val: number, i: number) => ({ time: (i + 1) * 5, wpm: val, wordCount: 0 }))
                                }
                            />
                        </div>
                    </div>

                    {/* Interval Breakdown Table moved to Page 3 */}
                </div>


            </PrintablePage>

            {/* PAGE 3: Interval Breakdown (Dedicated Page) */}
            <PrintablePage pageNum={3} totalPages={4}>
                <div className="flex-1">
                    <h4 className="text-lg font-bold text-slate-900 mb-6 flex items-center gap-2 pb-4 border-b border-slate-100">
                        <Activity className="w-5 h-5 text-purple-600" /> Interval Breakdown
                    </h4>

                    {/* Interval Breakdown Table - Full Page Mode */}
                    <div className="border border-slate-200 rounded-xl overflow-hidden bg-white mb-8">
                        <div className="grid grid-cols-12 gap-4 px-6 py-3 bg-slate-100 border-b border-slate-200 text-xs font-bold text-slate-500 uppercase tracking-wider">
                            <div className="col-span-3">Time</div>
                            <div className="col-span-7">Pace Visualization</div>
                            <div className="col-span-2 text-right">WPM</div>
                        </div>
                        <div className="divide-y divide-slate-100">
                            {pacingBuckets.length > 0 ? pacingBuckets.map((b, i) => (
                                <div key={i} className="grid grid-cols-12 gap-4 px-6 py-3 items-center text-sm">
                                    <div className="col-span-3 font-mono text-slate-600 text-xs">{b.intervalLabel}</div>
                                    <div className="col-span-7">
                                        <div className="h-2 bg-slate-100 rounded-full overflow-hidden">
                                            <div className={`h-full rounded-full ${b.color}`} style={{ width: `${Math.min((b.wpm / 180) * 100, 100)}%` }} />
                                        </div>
                                    </div>
                                    <div className={`col-span-2 text-right font-mono font-bold ${b.textColor}`}>{b.wpm}</div>
                                </div>
                            )) : (
                                <div className="p-4 text-center text-slate-400 italic text-xs">No interval data recorded.</div>
                            )}
                        </div>
                    </div>
                </div>
                {/* Recommendations (Moved to Page 3) */}
                <div className="flex-1 mt-4">
                    <h4 className="text-lg font-bold text-slate-900 mb-6 flex items-center gap-2 pb-4 border-b border-slate-100">
                        <span>💡</span> Coach's Recommendations
                    </h4>
                    <ul className="space-y-4">
                        {data.tips.map((tip: string, index: number) => (
                            <li key={index} className="flex gap-4 items-start text-sm text-slate-700 p-4 bg-slate-50 rounded-xl border border-slate-200 shadow-sm">
                                <span className="w-6 h-6 rounded-full bg-blue-600 text-white flex items-center justify-center text-xs font-bold shrink-0 shadow-md">
                                    {index + 1}
                                </span>
                                <div className="leading-relaxed">
                                    <h5 className="font-bold text-slate-900 mb-0.5">Observation {index + 1}</h5>
                                    {tip}
                                </div>
                            </li>
                        ))}
                    </ul>
                </div>
                <div className="flex-1"></div>
            </PrintablePage>

            {/* PAGE 4: Full Transcript */}
            <PrintablePage pageNum={4} totalPages={4}>
                <h2 className="text-xl font-bold text-slate-900 mb-6 flex items-center gap-2 pb-4 border-b border-slate-100">
                    <Mic className="w-5 h-5 text-blue-600" /> Full Transcript
                </h2>
                <div className="flex-1 bg-slate-50 rounded-xl p-8 border border-slate-200 text-sm leading-relaxed text-slate-700 whitespace-pre-wrap font-serif">
                    {metrics.transcript ? metrics.transcript : <em className="text-slate-400">No transcript available for this session.</em>}
                </div>
            </PrintablePage>
        </div>
    );
}
